services:
  rpg_database:
    platform: linux/x86_64
    image: mysql
    container_name: rpg_database
    ports:
      - "3306:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: RpgDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    networks:
      - database

  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq

  rpg_api:
    container_name: rpg_api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "10001:80"
      - "10002:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - rpg_database
      - rabbitmq
    volumes:
      - ./:/app/app
    links:
      - rpg_database
      - rabbitmq
    networks:
      - rabbitmq
      - database

networks:
  rabbitmq:
    name: rabbitmq
  database:
    name: database